server:
  port: 9277
  #\u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  eureka:
    client:
      serviceUrl:
        defaultZone: http://locahost:9277/eureka/
      #\u670D\u52A1\u540D
      spring:
        application:
          name: shangping-service
